---
# tasks file for cloud-config

- name: Copy cloud config files to remote host
  copy:
    src: "{{ item.name }}"
    dest: "{{ SASHOME }}/{{ item.path }}/{{ item.name }}"
    owner: "{{ INSTALL_USER }}"
    group: "{{ INSTALL_GROUP }}"
    mode: "{{ item.mode }}"
  with_items:
  - { name: docker-functions, path: "lib/envesntl", mode: "0755" }
  - { name: docker-ops-agent, path: "lib/envesntl", mode: "0755" }
  - { name: consul-utils.sh, path: "bin", mode: "0755" }
  - { name: kill_consul_helper.sh, path: "bin", mode: "0755" }
  - { name: localconsul_generate_vault_cert.sh, path: "bin", mode: "0755" }
  - { name: sas-consul, path: "bin", mode: "0755" }

- name: Adjust for running as the sas user
  shell: |
    sed -i 's|\$RU \$uid -c "\$\*".*$|\$\*|g' {{ SASHOME }}/lib/envesntl/sas-init-functions
    for viya_process in $(ls -1 /etc/init.d/sas-{{ DEPLOYMENT_ID }}-*); do
        if [[ "${viya_process}" != *"sas-{{ DEPLOYMENT_ID }}-all-services" ]] &&
          [[ "${viya_process}" != *"sasgpud"* ]] &&
          [[ "${viya_process}" != *"sas-{{ DEPLOYMENT_ID }}-vault"* ]] &&
          [[ "${viya_process}" != *"sas-{{ DEPLOYMENT_ID }}-ops-agent-"* ]]; then
            sed -i 's|^SASLOCKROOT="/var/lock/subsys"|SASLOCKROOT="/opt/sas/{{ DEPLOYMENT_ID }}/config/var/lock"|g' ${viya_process}
        fi
    done
