---
# tasks file for cloud-config

- name: Copy cloud config files to remote host
  copy:
    src: "{{ item.name }}"
    dest: "{{ SASHOME }}/{{ item.path }}/{{ item.name }}"
    owner: "{{ INSTALL_USER }}"
    group: "{{ INSTALL_GROUP }}"
    mode: "{{ item.mode }}"
  with_items:
  - { name: docker-functions, path: "lib/envesntl", mode: "0755" }
  - { name: docker-ops-agent, path: "lib/envesntl", mode: "0755" }
  - { name: consul-utils.sh, path: "bin", mode: "0755" }
  - { name: kill_consul_helper.sh, path: "bin", mode: "0755" }
  - { name: localconsul_generate_vault_cert.sh, path: "bin", mode: "0755" }
  - { name: sas-consul, path: "bin", mode: "0755" }
  - { name: setup_rds_postgres.sh, path: "bin", mode: "0755" }
