---
# tasks file for SAS Viya service

- name: Load the {{ role_name }} variables
  include_vars:
    file: "{{ role_name }}"
    name: sas_host_group_variables

- name: Install SAS packages
  include_role:
    name: sas-install

- name: Check dir presence for entrypoint
  file:
    path: "{{ SASHOME }}/bin"
    state: directory

- name: Copy over entrypoint script
  template:
    src: entrypoint
    dest: "{{ SASHOME }}/bin/{{ role_name|lower }}-entrypoint.sh"
    mode: "0755"
    owner: "{{ INSTALL_USER }}"
    group: "{{ INSTALL_GROUP }}"

- name: chown directories
  file: path="{{ item }}" owner="{{ INSTALL_USER }}" group="{{ INSTALL_GROUP }}" state=directory recurse=yes
  with_items:
    - /etc/httpd
    - /var/www
    - /var/run/httpd
    - /var/log/httpd

- name: chown files
  file: path="{{ item }}" owner="{{ INSTALL_USER }}" group="{{ INSTALL_GROUP }}" 
  with_items:
    - /etc/pki/tls/certs/localhost.crt
    - /etc/pki/tls/private/localhost.key
