---
# tasks file for SAS Viya service

- name: Load the {{ role_name }} variables
  include_vars:
    file: "{{ role_name }}"
    name: sas_host_group_variables

- name: Install SAS packages
  include_role:
    name: sas-install

- name: Copy over entrypoint script
  template:
    src: entrypoint
    dest: "{{ SASHOME }}/bin/{{ role_name|lower }}-entrypoint.sh"
    mode: "0755"
    owner: "{{ INSTALL_USER }}"
    group: "{{ INSTALL_GROUP }}"

- name: Set Ownership of rabbitmq directory
  shell: |
    export RABBITMQ_DATA_DIR=/rabbitmq/data
    export SASROOT=/opt/sas
    export SASDEPLOYID=viya
    export SASCONFIG=${SASROOT}/${SASDEPLOYID}/config
    chown -v sasrabbitmq:sas /opt/sas/viya/config/var/lib/rabbitmq-server/sasrabbitmq
    if [ ! -d ${RABBITMQ_DATA_DIR} ]; then
       mkdir -vp ${RABBITMQ_DATA_DIR}
       chown -v sasrabbitmq:sas ${RABBITMQ_DATA_DIR}
       chmod -v 0755 ${RABBITMQ_DATA_DIR}
    fi
    chown -vR sasrabbitmq:sas "$(dirname "${RABBITMQ_DATA_DIR}")"
    if [[ -e ${SASCONFIG}/etc/SASSecurityCertificateFramework/tokens/rabbitmq/default/erlang.cookie ]];then
       cp ${SASCONFIG}/etc/SASSecurityCertificateFramework/tokens/rabbitmq/default/erlang.cookie ${SASCONFIG}/var/lib/rabbitmq-server/sasrabbitmq/.erlang.cookie
       chown sasrabbitmq:sas ${SASCONFIG}/var/lib/rabbitmq-server/sasrabbitmq/.erlang.cookie
       chmod 600 ${SASCONFIG}/var/lib/rabbitmq-server/sasrabbitmq/.erlang.cookie
    fi
    sed -i "s|RABBITMQ_USER=sasrabbitmq|RABBITMQ_USER=sas|" /opt/sas/viya/home/bin/sas-rabbitmq-server
    sed -i "s|id -u sasrabbitmq|id -u sas|" /opt/sas/viya/home/sbin/rabbitmq-server
    sed -i "s|id -u sasrabbitmq|id -u sas|" /opt/sas/viya/home/sbin/rabbitmq-plugins
    sed -i "s|id -u sasrabbitmq|id -u sas|" /opt/sas/viya/home/sbin/rabbitmqctl
    sed -i 's|sasrabbitmq:sas|sas:sas|' /opt/sas/viya/home/bin/sas-rabbitmq-registration
    sed -i 's|SASUSER=sasrabbitmq|SASUSER=sas|' /etc/init.d/sas-viya-rabbitmq-server-default
