---
# tasks file for SAS Viya service

- name: Load the {{ role_name }} variables
  include_vars:
    file: "{{ role_name }}"
    name: sas_host_group_variables

- name: Install SAS packages
  include_role:
    name: sas-install

- name: Check dir presence for entrypoint
  file:
    path: "{{ SASHOME }}/bin"
    state: directory

- name: Copy over entrypoint script
  template:
    src: entrypoint
    dest: "{{ SASHOME }}/bin/{{ role_name|lower }}-entrypoint.sh"
    mode: "0755"
    owner: "{{ INSTALL_USER }}"
    group: "{{ INSTALL_GROUP }}"

- name: Comment out conflicting X-Forwarded headers
  shell: |
    LINE_NUM=$(grep -n '# Default the X-Forwarded-Proto header to http' /etc/httpd/conf.d/petrichor.conf|cut -f1 -d:)
    if [[ $LINE_NUM -gt 0 ]]; then
        END_LINE=$(($LINE_NUM+7))
        sed -ibak "$LINE_NUM,$END_LINE {s/^/#/}" /etc/httpd/conf.d/petrichor.conf
    fi
